version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: perDiem
    expose:
    - "5433"
    ports:
      - '5433:5433'
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -p 5433

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: nest_api
    ports:
      - '4000:4000'
    env_file:
      - ./apps/api/.env
    depends_on:
      - postgres


  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: next_web
    ports:
      - '3000:3000'
    env_file:
      - ./apps/web/.env
    depends_on:
      - api

volumes:
  pgdata:
