version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: db_postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: perDiem
    ports:
      - '5433:5433'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    command: -p 5433

  api:
    image: node:20-alpine
    container_name: nest_api_dev
    working_dir: /app
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    env_file:
      - ./apps/api/.env
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5433/perDiem
    entrypoint: >
      sh -c "
      apk add --no-cache bash git python3 make g++ &&
      npm install &&
      npx prisma migrate deploy &&
      npx prisma generate &&
      npm run start:dev
      "


  web:
    image: node:20-alpine
    container_name: next_web_dev
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./apps/web/.env
    depends_on:
      - api
    entrypoint: >
      sh -c "
      apk add --no-cache bash git python3 make g++ &&
      npm install &&
      npm run dev
      "

volumes:
  pgdata_dev:
